### PR TITLE
Set atime and mtime of extracted tar files

### PR DESCRIPTION
**Pull request by AlexandreCarlton**
Currently, `go-getter` will not set the original `atime` and `mtime` attributes when extracting files and directories. If we use it to download the [latest `go` release](https://dl.google.com/go/go1.9.2.linux-amd64.tar.gz) for example, we will see (using `ls -g`):

```
total 132
drwxr-xr-x 1 alexandre   224 Jan 21 11:43 api
drwxr-xr-x 1 alexandre    24 Jan 21 11:43 bin
drwxr-xr-x 1 alexandre    30 Jan 21 11:43 blog
drwxr-xr-x 1 alexandre   976 Jan 21 11:43 doc
drwxr-xr-x 1 alexandre     8 Jan 21 11:43 lib
drwxr-xr-x 1 alexandre   144 Jan 21 11:43 misc
drwxr-xr-x 1 alexandre   118 Jan 21 11:43 pkg
drwxr-xr-x 1 alexandre   888 Jan 21 11:43 src
drwxr-xr-x 1 alexandre  5906 Jan 21 11:43 test
-rw-r--r-- 1 alexandre 41258 Jan 21 11:43 AUTHORS
-rw-r--r-- 1 alexandre  1576 Jan 21 11:43 CONTRIBUTING.md
-rw-r--r-- 1 alexandre 55577 Jan 21 11:43 CONTRIBUTORS
-rw-r--r-- 1 alexandre  5686 Jan 21 11:43 favicon.ico
-rw-r--r-- 1 alexandre  1479 Jan 21 11:43 LICENSE
-rw-r--r-- 1 alexandre  1303 Jan 21 11:43 PATENTS
-rw-r--r-- 1 alexandre  1601 Jan 21 11:43 README.md
-rw-r--r-- 1 alexandre    26 Jan 21 11:43 robots.txt
-rw-r--r-- 1 alexandre     7 Jan 21 11:43 VERSION
```
As the `atime` and `mtime` of files are not currently set, they default to the time they were extracted instead of the times in the original files.

With this PR, we now get:

```
total 132
drwxr-xr-x 1 alexandre   224 Oct 26 05:34 api
drwxr-xr-x 1 alexandre    24 Oct 26 05:40 bin
drwxr-xr-x 1 alexandre    30 Oct 26 05:40 blog
drwxr-xr-x 1 alexandre   976 Oct 26 05:34 doc
drwxr-xr-x 1 alexandre     8 Oct 26 05:34 lib
drwxr-xr-x 1 alexandre   144 Oct 26 05:40 misc
drwxr-xr-x 1 alexandre   118 Oct 26 05:40 pkg
drwxr-xr-x 1 alexandre   888 Oct 26 05:34 src
drwxr-xr-x 1 alexandre  5906 Oct 26 05:40 test
-rw-r--r-- 1 alexandre 41258 Oct 26 05:34 AUTHORS
-rw-r--r-- 1 alexandre  1576 Oct 26 05:34 CONTRIBUTING.md
-rw-r--r-- 1 alexandre 55577 Oct 26 05:34 CONTRIBUTORS
-rw-r--r-- 1 alexandre  5686 Oct 26 05:34 favicon.ico
-rw-r--r-- 1 alexandre  1479 Oct 26 05:34 LICENSE
-rw-r--r-- 1 alexandre  1303 Oct 26 05:34 PATENTS
-rw-r--r-- 1 alexandre  1601 Oct 26 05:34 README.md
-rw-r--r-- 1 alexandre    26 Oct 26 05:34 robots.txt
-rw-r--r-- 1 alexandre     7 Oct 26 05:34 VERSION
```
which is consistent with how `tar` extracts regular files and directories.

We must take care to set the `atime` and `mtime` of the directories after all files have been extracted, since the addition of a file to a directory changes its `mtime`.

### CODE REVIEW

**Comment by schmichael** [comment]
Could you add a test? I'm afraid you'll have to alter the TestDecompress test helper:

- Add Atime and Mtime fields [here](https://github.com/hashicorp/go-getter/blob/master/decompress_testing.go#L24)
- Assert the Atimes and Mtimes are what you expect in the [test function](https://github.com/hashicorp/go-getter/blob/master/decompress_testing.go#L41-L87)
- Get expected Atimes and Mtimes from the fixtures [here](https://github.com/hashicorp/go-getter/tree/master/test-fixtures/decompress-tar)
- Add the expected Atimes and Mtimes [here](https://github.com/hashicorp/go-getter/blob/master/decompress_tar_test.go#L22)

**Comment by schmichael** [comment]
And thanks for the PR! Looks great!

**Comment by AlexandreCarlton** [comment]
Thanks for both of your feedback, it was super helpful in making a test for this. :)

I should note that I only ended up testing `mtime` and not `atime`, since the latter is updated every time it is accessed (and so would be spoiled by an `os.Stat` to check it).

I've also moved the `dirHdrs` loop out of the main loop as requested.

**Comment by mitchellh** [comment]
Thanks for adding the tests, and the code architecture changes look great as well. Merged!

**Pull request merged**
