### PR TITLE
link in support for the tarDecompressor, so it can be used on .tar files

### LINKED ISSUE #19: Add support for tar archives
Some projects distribute with .zip or .tgz, others have only a .tar (example: https://github.com/AcalephStorage/consul-alerts distributes https://bintray.com/artifact/download/darkcrux/generic/consul-alerts-latest-linux-amd64.tar)

It seems that the go-getter library only supports .tgz or .bz2, but not uncompressed .tar by itself.

### PR DESCRIPTION
**Pull request by ketzacoatl**
resolve #19.

### CODE REVIEW

**Comment by leprechau** [comment]
LGTM ... this should work.  I think it makes sense to go ahead and export `tarDecompressor` as `TarDecompressor` for consistency.

**Comment by ketzacoatl** [comment]
@leprechau would that be as simple as renaming https://github.com/hashicorp/go-getter/blob/master/decompress_tar.go#L138-L142 (and the reference in my PR), or is there more to do to export the `TarDecompressor` correctly?

**Comment by ketzacoatl** [comment]
This ought to make it easier to resolve https://github.com/hashicorp/nomad/issues/2443.

**Review by schmichael — APPROVED** [review]
Sorry this fell through the cracks. Merging and can export tarDecompressor in a followup. Doing so here would require resolving a merge conflict.

**Comment by ketzacoatl** [comment]
Yay! Thanks @schmichael!

**Pull request merged**
