### PR TITLE
Azure blob

### LINKED ISSUE #33: Add Azure Blob Storage Support
Allow go-getter to download artifacts from Azure Blob Storage private containers.

S3 is already supported, this is a feature request to have same functionality for Azure Blob Storage.

### PR DESCRIPTION
**Pull request by larsmaes**
Fixes #33 
Replaces #222 

This is my first PR so please feel free to discus

### CODE REVIEW

**Comment by larsmaes** [comment]
I have used my own azure storage acccount for testing. I think it would be better to use a hashicorp provided storage account. Is there anyone in here that can deliver it?

**Comment by brentmannering** [comment]
@crw would you be able to nudge the Azure Provider team again please? 
Support for blob storage has been requested for a number of years, with a number of people submitting PR's, this PR is just the most recent. It would be great to get this in so other tools like terraform can be enhanced and benefit from it.

**Comment by manicminer** [comment]
@larsmaes Thanks for opening this PR, apologies for the delay in reviewing. Whilst this is a feature we would be happy to add, unfortunately this PR is using the `github.com/Azure/azure-sdk-for-go` SDK, which we do not wish to use for a number of reasons. At this time, the supported SDK for Azure Storage can be found at https://github.com/jackofallops/giovanni - the implementation is much simpler and leans on [our in-house Azure SDK](https://github.com/hashicorp/go-azure-sdk) for authentication and transport.

As such, whilst we'd like to add this features, we wouldn't be able to merge this in its current form. I'll go ahead and close this PR since unfortunately switching the SDK would essentially require reworking the entire change, but we can certainly look at merging a PR that uses our supported SDK.

**Comment by zsd4yr** [comment]
Hey @manicminer thanks for the feedback here :) 

Can you share some of the concerns you have with the official azure go sdk?

**Pull request closed without merging**
