### PR TITLE
Add failing cases for SCP style git "URLs"

### PR DESCRIPTION
**Pull request by paultyng**
Some additional detection cases:

1. SSH URL syntax this case passes
2. SCP style with forced getter and pwd, this fails with detection as file URL
3. SCP style with forced getter (no pwd), this fails with no PWD error in file detector

### CODE REVIEW

**Comment by paultyng** [comment]
Its possible the fix in #38 would work here?

**Comment by paultyng** [comment]
Some TF issue references:
https://github.com/hashicorp/terraform/issues/18869
https://github.com/hashicorp/terraform/issues/18566
https://github.com/hashicorp/terraform/issues/18546
https://github.com/hashicorp/terraform/issues/18541

**Comment by apparentlymart** [comment]
My expectation is that the "force" syntax should actually force, by which I mean not run any detectors _at all_.

The file detector also seems broken in that it just assumes everything is a file, rather than actually checking.

Of course, both of these odd behaviors have been present for years so it is odd that they have only recently started causing so much trouble. Changing them now may break someone relying on one or both of them. ☹️

**Comment by paultyng** [comment]
Yeah that's my worry as well

**Comment by apparentlymart** [comment]
On the other hand, given that almost all of the behavior here emerges by coincidence rather than specification, "changing it may break someone" could apply to _any_ change right now. This never gets easier to fix, so maybe a path forward here is:

* Go Modules-ize this repository and tag the exact current state as 1.0 retroactively, matching what we've done with other Go library codebases since Go Modules was released.
* Specify some reasonable and deliberate behavior for how we intend "addresses" to work in this library, bringing forward the _spirit_ of the current implementation and exact compatibility with the most common usages that have been featured in application docs, etc.
* Implement that new behavior, accepting that it may change some behaviors around the edges, and tag it as 2.0.
* Include go-getter 2.0 in a future _major_ release of each application, staying exactly frozen on a particular old implementation until the application is ready to make such a major release.

I don't really see any way to avoid the compatibility risk, so it seems like the options are either to never change this library's behavior again (impractical) or to accept and manage the risk.

**Comment by mitchellh** [comment]
I'll respond here quickly: I'll take a look at this next week when I'm back but can explain why some things behave the way they do.

The reason we run `Detect` even if forced is because the final input to the "getter" implementation must be a valid URL. So Detect converts the value to a valid URL, but it always routes it to the correct forced getter (or it should!).

The reason the "File" detecter just accepts almost anything is historically from Vagrant: file paths are quite creative across systems so attempting to standardize on them is almost always a cat/mouse game. Even major filesystems such as Windows have extremely weird file paths (by Unix standards) when accessing things like network group machines, in addition to other bizarre edge cases. So it is the last fallback/assumption to try.

I think this is all fixable though so let me take a look next week! :)

**Comment by paultyng** [comment]
I cleaned up the test cases I had appended and added a proposal to fix this, let me know your thoughts when you are back!

**Comment by mitchellh** [comment]
Closing for #129 

Thanks @paultyng for your work! I ended up leaning on it pretty heavily. The one major change I made was keeping the "GitHubDetector" in addition to a generic "GitDetector." I thought it was weird to mix the magical "github.com/" string prefix detection with the more generic stuff, so they both ended up being separate and fairly lightweight detectors instead.

I dug into your linked TF issues (thanks!) too and found a second bug at play there, also fixed in #129 and detailed there. All should be good now.

**Pull request closed without merging**
