### PR TITLE
[WIP] s3: Retrieves credentials from different providers

### PR DESCRIPTION
**Pull request by c4milo**

### CODE REVIEW

**Comment by mitchellh** [comment]
What does this do?

**Comment by c4milo** [comment]
Apologies for not clarifying in the description. This is a work in progress. For the S3 getter since it is missing retrieving the actual credentials from the providers defined when instantiating `credentials.NewChainCredentials()`

**Comment by mitchellh** [comment]
Thanks, please put a WIP in the title and/or description next time. The AWS SDK itself should be calling `Get`...

**Comment by mitchellh** [comment]
See your original issue I believe this is fixed!

**Pull request closed without merging**
