### PR TITLE
add zstd support 

### LINKED ISSUE #270: Support zstd
It's much much faster than xz for both compression and decompression while maintaining similar result.

There are 2 implementation available for go, both are 3 clause BSD

https://github.com/DataDog/zstd  the go wrapper for facebook/zstd
https://github.com/klauspost/compress  a pure go implementation but around 1.5x slower than C implementation (https://github.com/dgraph-io/badger/pull/1176#issuecomment-573635053)

### PR DESCRIPTION
**Pull request by yaroot**
It's pretty straightforward and I went with the pure go implementation.

closes #270

### CODE REVIEW

**Comment by jboero** [comment]
Wow fantastic.  I just came back today to throw this together but you've already done it.  Thank you!

**Comment by jboero** [comment]
@yaroot 
Is this single threaded or does it support parallel zstd?

**Comment by yaroot** [comment]
> Is this single threaded or does it support parallel zstd?

It's single threaded

**Comment by jboero** [comment]
@schmichael Can we please get this in?  Very exciting. Thanks.

**Review by schmichael — APPROVED** [review]

**Review by azr — APPROVED** [review]

**Comment by schmichael** [comment]
Thanks @yaroot !

**Pull request merged**
