### PR TITLE
go get cloud.google.com/go@v0.45.1

### PR DESCRIPTION
**Pull request by apparentlymart**
The primary motivation of this is that this old version of `cloud.google.com/go` depends on an old version of `go.opencensus.io` which in turn depends on `git.apache.org/thrift.git`. That is old mirror of the Thrift repository that is no longer canonical and is currently down.

We don't need Thrift in our dependency graph at all here, and we only had it in the first place because `go.opencensus.io` was depending on it. Newer versions of that library don't include a Thrift client in the main library and so we don't inherit that transitive dependency anymore.

This also cleans up some accumulated checksums that we no longer need from the `go.sum` file.

### CODE REVIEW

**Comment by apparentlymart** [comment]
The Travis-CI failure here is coming from this being the first time we've run against the latest Go 1.11 release that has the new check in `net/uri` to force port numbers to be numeric. We already had a check for that in `go-getter` but the tests fail now because the error message text has changed from _our_ message to the `net/uri` message.

This doesn't appear to have anything to do with upgrading `cloud.google.com/go` so I'd like to move forward with this as-is and address this unrelated failure separately. The appveyor tests, which ran against a different version of Go, show this succeeding as expected.

**Comment by vsimon** [comment]
> This doesn't appear to have anything to do with upgrading cloud.google.com/go so I'd like to move forward with this as-is and address this unrelated failure separately. 

yes please

**Comment by dmitshur** [comment]
Thanks for merging this change. Are you planning to create a new release that will include this change?

**Comment by azr** [comment]
Sure ! I think first we need to address #203 because a somewhat breaking change in `net.URL` might break the go-getter's url parser/validator 🙂.

**Pull request merged**
